### ISSUE TITLE
Documentation for replacement of MIME::Types#index_extensions

### ISSUE THREAD

**Issue by haslinger** [halostatue/mime-types#88]
I learn that MIME::Types#index_extensions is deprecated and will be private.
What's the suggested way to go these days? 
A note in the documentation about it would be nice.

**Comment by halostatue** [comment]
There is currently no replacement planned; I am aware that there is a problem where the extensions need to be updated.

Can you indicate your use case?

**Comment by haslinger** [comment]
Thanks for your quick reply! 
I'm coming here from using Paperclip (the attachment-upload gem) where the method is recommended for fixing inconsistencies. To be more precise, I've got ogg-audio-files which are .ogg, but declare themselves as video/ogg when uploaded.
Maybe it's better than I tell Paperclip about the deprecation?
(Off topic: Thank you for your work! It's people like you, who provide infrastructure for devs like me, I very much appreciate it.)

**Comment by halostatue** [comment]
As I understand it, when I figure out a fix for #84, this should also be fixed.

**Comment by haslinger** [comment]
Yep, so I no follow the #84 and close here.
